### ISSUE TITLE
How to add to my BMC system?

### ISSUE THREAD

**Issue by luoshuai777** [zhangjian3032/tutorial#1]
Hi~,
      I want to test this daemon you wrote, but I don't know how to add the dependency library in my .bb,i need your help

**Comment by zhangjian3032** [comment]
@luoshuai777 
I just wrote one, hope it can help you

```
LICENSE = "CLOSED"
SUMMARY = "My tutorial"
DESCRIPTION = "Providing "

SRC_URI += "git://github.com/zhangjian3032/tutorial;protocol=https;branch=main"
SRCREV = "${AUTOREV}"

PR = "r1"

PV = "1.0+git${SRCPV}"

inherit meson
inherit pkgconfig
inherit systemd

S = "${WORKDIR}/git"

DEPENDS = " \
         phosphor-logging \
         phosphor-dbus-interfaces \
         sdbusplus \
         ${PYTHON_PN}-sdbus++-native \
         i2c-tools \
         ${PYTHON_PN}-native \
         ${PYTHON_PN}-pyyaml-native \
         ${PYTHON_PN}-setuptools-native \
         ${PYTHON_PN}-mako-native \
         libevdev \
         sdeventplus \
         "
```

**Comment by luoshuai777** [comment]
First of all, thanks a lot, refer to your bb can be added to my BMC. But after starting my bmc, I don't see any related service, obj path, and interface using busctl tree, systemctrl.

I read your article from Zhihu and came here, I have a few questions for you, I think we can communicate in Chinese, because my English is not good, I am sorry.

**Comment by zhangjian3032** [comment]
@luoshuai777 
>  I don't see any related service,
因为这个是一个例子, 没有安装任何service, 如果你需要任何service, [参考此链接](https://github.com/openbmc/x86-power-control/blob/master/service_files/xyz.openbmc_project.Chassis.Control.Power%40.service) 

Cheers

**Comment by luoshuai777** [comment]
谢谢健哥，根据您的例子，我添加了service：
![image](https://user-images.githubusercontent.com/57705487/220852505-82106972-08ad-4b58-b716-e088f4478ab3.png)
现在我想把添加的intertface的property值显示到页面上去，这里需要通过redfish来获取吧，应该怎么做呢，您能给点建议吗，或者有相关的example，感谢！

**Comment by zhangjian3032** [comment]
> 现在我想把添加的intertface的property值显示到页面上去 

页面? 什么页面? 前端?
> 这里需要通过redfish来获取吧，应该怎么做呢，您能给点建议吗，或者有相关的example，感谢！

redfish 只是后端, 参考bmcweb 的代码, https://github.com/openbmc/bmcweb

**Comment by luoshuai777** [comment]
> 页面? 什么页面? 前端?
是的，前端，也就是显示到网页上去。

我理解的是：前端会发送一个请求，后端收到后，redfish会去对应的dbus路径上获取property的值？
我根据bmcweb中一些readme，暂时还不理解我需要做哪些工作。

**Comment by zhangjian3032** [comment]
1. bmcweb 里面添加 redfish 的api, 看看其他的地方怎么实现的
2. 前端代码也添加一下, 因为我不看前端, 给不了建议

**Comment by luoshuai777** [comment]
好的，感谢！

**Comment by luoshuai777** [comment]
健哥，您好！
再跟您请教个问题，根据您的示例:tutorial/10_dbus_matches/10_1_interfaceAdded_yaml_object_interface_specific_manager_object/main_server.cpp，我添加代码按如下图例添加，目前程序跑完只能修改一次property属性值，如果想要实时更新的话，应该怎么做呢？
![image](https://user-images.githubusercontent.com/57705487/223084284-ce62eeab-a1d1-44d4-9443-5acdd98149d0.png)

**Comment by zhangjian3032** [comment]
.... 我觉得你应该学会怎么提问, your question are always too vague!
